# Generated by Django 4.2.6 on 2023-10-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_jacket_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='image_url',
            field=models.CharField(default='toto', max_length=5000),
            preserve_default=False,
        ),
    ]
