# Generated by Django 4.2.6 on 2023-10-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_jacket_app', '0002_brandmodel_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodel',
            name='tarif',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
