# Generated by Django 4.2.6 on 2023-10-25 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('green_jacket_app', '0003_brandmodel_tarif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandmodel',
            name='shop_cart',
        ),
        migrations.AddField(
            model_name='shopcart',
            name='brand_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shop_carts', to='green_jacket_app.brandmodel'),
            preserve_default=False,
        ),
    ]
