# Generated by Django 4.2.6 on 2023-10-25 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('green_jacket_app', '0004_remove_brandmodel_shop_cart_shopcart_brand_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='green_jacket_app.brandmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='green_jacket_app.usercustom')),
            ],
        ),
        migrations.DeleteModel(
            name='ShopCart',
        ),
    ]
